abstract/put-get-del-test.js
Closes https://github.com/Level/abstract-leveldown/issues/55
=> convert buffer to string so we can compare

package.json, test.js
I'm starting here, then moving to `leveldown` and then `levelup`.
/cc @mcollina @juliangruber
=> change from tap to tape

abstract-leveldown.js, abstract/leveldown-test.js
Closes https://github.com/Level/abstract-leveldown/issues/59
=> Empty location

abstract-leveldown.js, test.js
required for https://github.com/Level/levelup/pull/342
cc @ralphtheninja
=> add .status

.travis.yml, README.md, package.json
=> update dependencies + badge

README.md
Closes https://github.com/Level/abstract-leveldown/issues/112
=> document .status property

abstract-leveldown.js, test.js
Rebased https://github.com/Level/abstract-leveldown/pull/99 and added test for `undefined`
=> null and undefined serializes to empty string

index.d.ts
=> Fix implicit any errors in index.d.ts

abstract-leveldown.js
=> Batch array: use xtend instead of object.assign

abstract/approximate-size-test.js, abstract/del-test.js, abstract/get-test.js
=> Remove test: serialize object key in approximateSize()

abstract-leveldown.js, abstract/batch-test.js
See #146.
Sometime later, we should remove levelup's logic for this.
=> Batch: assert type is 'put' or 'del'

abstract/put-get-del-test.js
Resolves https://github.com/Level/abstract-leveldown/issues/155
=> remove BufferType, use Buffer

abstract-leveldown.js
Closes https://github.com/Level/abstract-leveldown/issues/153
=> cleanup if statement

abstract-chained-batch.js, abstract-leveldown.js
Resolves https://github.com/Level/abstract-leveldown/issues/149
=> Buffer.isBuffer()

abstract/put-test.js
=> Remove object value test

README.md, abstract-leveldown.js, test.js
Closes https://github.com/Level/abstract-leveldown/issues/154
Will squash this.
=> Setup iterator options

UPGRADING.md
Closes https://github.com/Level/abstract-leveldown/issues/185
=> add UPGRADING.md

README.md
Closes https://github.com/Level/abstract-leveldown/issues/189
=> readme: link to upgrade guide

CHANGELOG.md, abstract-iterator.js, abstract/iterator-test.js, index.d.ts, test-types.ts
Fixes https://github.com/Level/leveldown/issues/443#issuecomment-364437129. I also updated the TypeScript typings @Level/typescript.
Should be released asap.
=> Fix iterator#next to return this

CHANGELOG.md, UPGRADING.md
Closes https://github.com/Level/abstract-leveldown/issues/225
=> Prepare 5.0.0

package.json, testCommon.js
Closes https://github.com/Level/abstract-leveldown/issues/242
=> Refactor collectEntries() into level-concat-iterator

test.js, test/put-get-del-test.js
Closes https://github.com/Level/abstract-leveldown/issues/191
=> Remove empty errorValues() test

test/iterator-test.js
Closes https://github.com/Level/abstract-leveldown/issues/265
=> Remove deprecated snapshot test

package.json, test.js, test/batch-test.js, test/chained-batch-test.js, test/close-test.js, test/common.js, test/del-test.js, test/get-test.js, test/index.js, test/iterator-no-snapshot-test.js, test/iterator-range-test.js, test/iterator-snapshot-test.js, test/iterator-test.js, test/open-create-if-missing-test.js, test/open-error-if-exists-test.js, test/open-test.js, test/put-get-del-test.js, test/put-test.js, test/self.js
Do not merge, ~~I'm just exploring~~. This will make it much easier to update implementations, because they only have to call one function. @ralphtheninja WDYT?
Closes #157.
=> Export test suite as single function

test/batch-test.js, test/chained-batch-test.js, test/close-test.js, test/del-test.js, test/get-test.js, test/iterator-range-test.js, test/iterator-test.js, test/leveldown-test.js, test/open-create-if-missing-test.js, test/open-error-if-exists-test.js, test/open-test.js, test/put-get-del-test.js, test/put-test.js, test/util.js
Closes https://github.com/Level/abstract-leveldown/issues/267
=> module.exports -> exports

test/close-test.js, test/self.js
Closes https://github.com/Level/abstract-leveldown/issues/278
=> Add setUp and tearDown to test/close-test.js

test/batch-test.js, test/close-test.js, test/del-test.js, test/get-test.js, test/iterator-test.js, test/open-test.js, test/put-test.js
Closes https://github.com/Level/abstract-leveldown/issues/280
=> Make sure throw tests check error messages properly

test/index.js, test/leveldown-test.js, test/self.js
Closes https://github.com/Level/abstract-leveldown/issues/284
=> Add setUp and tearDown to test/leveldown-test.js

CHANGELOG.md
I ran through this pretty quickly so it's most likely a bit rough. PTAL.
=> Update changelog for v6

README.md
=> Add Spread The Word and Install sections

abstract-iterator.js
Closes https://github.com/Level/abstract-leveldown/issues/301
=> Fix bug in AbstractIterator#_seek

CHANGELOG.md, README.md, UPGRADING.md, abstract-chained-batch.js, abstract-iterator.js, test/chained-batch-test.js, test/iterator-test.js, test/self.js
=> Make db property mandatory and public on iterator and chained batch

.airtap.yml, CHANGELOG.md, CONTRIBUTORS.md, LICENSE.md, README.md, UPGRADING.md, package.json
=> Prepare 6.0.0

CHANGELOG.md, LICENSE.md, README.md, package.json
Squash on merge. Ref Level/community#29.
=> Apply common project tweaks

package.json, test/self.js
Ref https://github.com/substack/tape/issues/458. Closes #328.
=> Fix subtests by adding t.plan()

README.md
Closes #346. Makes `abstract-leveldown` seem more strict, but this aligns better with the test suite.
=> Document mandatory methods

test/manifest-test.js
See https://github.com/Level/subleveldown/pull/79#issuecomment-536915443.
=> Fix manifest-test to open & close its db
