Level/abstract-leveldown

abstract/put-test.js

This adds 2 sync put tests, trying to recreate the failure from https://github.com/Level/leveldown/issues/157. On leveldown@master, this does __not__ cause a segfault for me. A `.put()` after the db is fully closed however does.
Once this is merged, we can add it to backends supporting `{ sync }`.

add sync put tests

---

abstract-leveldown.js
index.js
is-leveldown.js
package.json
test.js

This adds the function `isLevelDOWN()` which I extracted from @substack 's commit https://github.com/substack/node-levelup/commit/cff0ae9fdf527569d20d48c73804dd8dafea2b59 (I'm cherry picking those commits to a new branch to make a new PR to levelup).
It basically makes sure the public api in `AbstractLevelDOWN` (except for the `approximateSize` method) is present in the given db object.

add isLevelDOWN() function

---

is-leveldown.js
test.js

I know `const` is nice, but PouchDB is kind of depending on MemDOWN for certain browser builds, so it would be preferable to have it work in ES5-compatible browsers.

(#71) - remove `const`

---

README.md

Since merging #77, the tests now run for all branches (which is good!). But the build status badge in the README.md showed the build status for the latest build - no matter the branch. So if a pull request failed its tests the main badge would show as failed on both npm and github.
This commit ensures that only the state of the master branch is reflected in the build status badge.
This commit also updates the badge URL to the latest recommend URL by Travis.

Only show build status for the master branch

---

README.md
abstract-chained-batch.js
abstract-leveldown.js
abstract/approximate-size-test.js
abstract/chained-batch-test.js
abstract/del-test.js
abstract/get-test.js
abstract/put-test.js
test.js

levelup handles massaging keys and values through its encoding layer already. However, if the user passed `encoding: 'id'`, abstract-leveldown would still convert everything to a string or buffer. For those encodings, like level.js and postgres-down that do support more of the native JS values, this gives them the chance of receiving the raw values and encoding them themselves.
It's a breaking change and so if merged will need a `3.0.0` release.

Remove stringification of keys and values

---

abstract/chained-batch-test.js

This PR addresses the main problem w/ the chained batch tests mentioned in #87 -- the tests assume an `_operations` buffer is kept in chained batch. This fixes the tests to capture the inputs that _would_ go to an `_operations` buffer, which is the data these tests are trying to introspecting.
/cc @ralphtheninja @juliangruber

Buffer _put/_del inputs in chained batch tests

---

abstract/approximate-size-test.js
abstract/chained-batch-test.js
abstract/del-test.js
abstract/get-test.js
abstract/put-test.js

This just loosens up the tests to allow _serlialize* functions to force buffers
for string keys or values. The underlying store impl might prefer (or require) buffers.
/cc @juliangruber @ralphtheninja

Allow serialization functions to return buffers

---

abstract/put-test.js
test.js

fixes https://github.com/Level/memdown/pull/57
Since abstract-leveldown implementers can choose to override `._serialize*` as they please, we really can't tell what kind of value we're getting. Simply checking for truthiness is like a smoke test for this behavior.
cc @nolanlawson @vweevers

fix put test on object serialization

---

abstract/chained-batch-test.js

* similar to the fix that was made in https://github.com/Level/abstract-leveldown/pull/100
* fixes tests for memdown

relax tests for serializing object in chained-batch-test.js

---

index.d.ts
package.json

* serves as the basis types for levelUP's db typings. 
* while there is a lot of generics, they allow for levelup's typing to infer them directly from the db passed to it. 
* used locally with current levelup and passes levelup's tests. 
* I've added an indexer on each interface to derived classes can access anything not defined without typing error.

feat: add generic typings

---

index.d.ts

*~~In the js files i've explicitly defined the abstract methods (as undefined). run-time wise it should _not_ make a difference as they are still equal to `undefined` - but it allows the ts compiler to stay happy when checking the js. This was an issue for me locally, as the `levelup` ts-test was throwing errors when the package was linked.~~ 
* moved batch and common iterator options into the abstract typings as they were missing.  
* reworked typings as es2015 module. 
* breaking. publish as minor. 
cc: @zixia you're using typescript? If so mind having a quick review of this?

refactor(typings): add missing types and simplify.

---

abstract-leveldown.js
test.js

Closes #136. Before this, the `_serializeKey` and `_serializeValue`  functions were only called if you used the chained batch form, not if you used the array form.

Fix: serialize batch

---

abstract/iterator-test.js

As discussed in #137.
This means that memdown can do:
```js
MemDOWN.prototype._serializeKey = function (key) {
return this._isBuffer(key)
? key
: String(key)
}
MemDOWN.prototype._serializeValue = function (value) {
if (value == null) return ''
return value
}
```
Instead of the default implementation of `_serializeValue`:
```js
MemDOWN.prototype._serializeValue = function (value) {
if (value == null) return ''
return this._isBuffer(value) || process.browser ? value : String(value)
}
```

Abstract tests: use strings for values

---

abstract-leveldown.js
abstract/batch-test.js

Closes #138.
Breaking change, major.

Batch array: assert elements are objects

---

abstract/approximate-size-test.js
abstract/chained-batch-test.js
abstract/del-test.js
abstract/get-test.js
abstract/put-test.js

These tests assert, for relevant methods like `_put`, that if the input is a Buffer, it is not touched.
However, this breaks an implementation like `localstorage-down` which cannot support Buffers natively, it has to convert Buffer keys and values to (base64) strings.
We don't need these tests (anymore) because for all the methods, we also have tests with a custom `_serializeKey` and/or `_serializeValue`. Which asserts that these methods do serialize. For example:
https://github.com/Level/abstract-leveldown/blob/49a1bd7156f3c476eda8f67e0f79946ce3674f3e/abstract/put-test.js#L79-L94
In addition, in the non-abstract test suite, we assert that the default `_serializeKey` and  `_serializeValue` leave Buffers alone:
https://github.com/Level/abstract-leveldown/blob/49a1bd7156f3c476eda8f67e0f79946 …

Remove serialize buffer tests

---

abstract/put-get-del-test.js
test.js

Resolves https://github.com/Level/abstract-leveldown/issues/126
Note that this doesn't remove `testBuffer`.
~~`db` is also a local global that could be called back in e.g. `.setUp(leveldown, test, testCommon, cb)` and later passed on as parameter to underlying functions.~~

test and testBuffer as parameters

---

abstract/batch-test.js
abstract/chained-batch-test.js
abstract/close-test.js
abstract/del-test.js
abstract/get-test.js
abstract/iterator-range-test.js
abstract/iterator-test.js
abstract/open-test.js
abstract/put-get-del-test.js
abstract/put-test.js

Closes https://github.com/Level/abstract-leveldown/issues/163
Also removes `testBuffer` in `put-get-del-test.js`

make testCommon.js the default value for testCommon parameter + remove testBuffer

---

README.md
abstract-chained-batch.js
abstract-iterator.js
abstract-leveldown.js
abstract/put-get-del-test.js
global.d.ts
index.d.ts
package.json
test-types.ts
test.js
tsconfig.json

Closes #190, #192, #193 (with a few leftover tasks I'll open issues for).

Add and fix TypeScript tests

---

index.d.ts
test.js

Tried using the typings with typescript 2.6/2.7 and neither worked. Both throw on `type Batch<K=any, V?=any>`. https://github.com/Level/abstract-leveldown/commit/b353fb45b00165222aa616111ddc8ae00e9a860a added the `?` before the default for some reason. AFAIK this is not valid typescript, and servers no purpose. Since `type Batch<K=any, V=any>` already has defaults, the values are optional. Without the question mark it seems to be working.
@vweevers can you elaborate on what you were trying to achieve?

Fix typings for Batch

---

README.md
abstract/iterator-no-snapshot-test.js
abstract/iterator-snapshot-test.js
abstract/iterator-test.js
test.js

Closes #165 and supersedes #46.
Implementations that cannot support snapshots, should include the `iterator-no-snapshot` test.

Isolate snapshot test

---

test.js
test/batch-test.js
test/chained-batch-test.js
test/close-test.js
test/del-test.js
test/get-test.js
test/iterator-no-snapshot-test.js
test/iterator-range-test.js
test/iterator-snapshot-test.js
test/iterator-test.js
test/leveldown-test.js
test/open-test.js
test/put-get-del-test.js
test/put-test.js

Closes https://github.com/Level/abstract-leveldown/issues/227

Merge factory function into testCommon parameter

---

test/iterator-range-test.js
test/self.js

Closes https://github.com/Level/abstract-leveldown/issues/270
I solved this differently, since `test/self.js` is calling `setUp()` and `tearDown()` we can't export a single `.all()` method.
Upgrade guide needs updating, because now _all_ test methods have the same api.

Lift out data to file scope to get rid of extra parameter

---

README.md
abstract-chained-batch.js
test/chained-batch-test.js
test/self.js

Tested against `leveldown` (but it will need some changes, because of https://github.com/Level/abstract-leveldown/issues/200#issuecomment-364128603).
Left to do:

Refactor chained batch

---

README.md
abstract-chained-batch.js
abstract-leveldown.js
test/batch-test.js
test/chained-batch-test.js
test/iterator-range-test.js
test/put-get-del-test.js
test/self.js

Closes #120, closes #130, closes #230. Checklist adapted from https://github.com/Level/abstract-leveldown/issues/120#issuecomment-390171073:
These are very tricky changes, will need canary testing in at least `leveldown`.
Externally (just mental notes):
- Add `leveldown#_serializeKey` and `#_serializeValue` (same logic) to convert nullish to an empty string, Buffer as-is, everything else to a string.

Serialization

---

abstract-leveldown.js

Closes https://github.com/Level/abstract-leveldown/issues/283

Add checks for null options (since typeof null === "object")

---

UPGRADING.md

I was thinking we could keep this branch alive and tweak the upgrade guide separately as we go. Then just squash it on top of everything, once we're done.

Update upgrade guide [wip]

---

README.md
UPGRADING.md
test/common.js
test/iterator-range-test.js
test/put-get-del-test.js

Closes #287 and I also added a `seek` option in anticipation of #269.
Tested against `leveldown` (to see that it ran the same number of tests).
With this, `process.browser` is gone! ~~But before we close #121 I wanna go through it, possibly open new issues for related stuff like https://github.com/Level/abstract-leveldown/issues/121#issuecomment-343722989.~~ *(done)*

Add 'bufferKeys' and 'seek' to skip options

---

README.md

Following the change in https://github.com/Level/leveldown/pull/506.

Readme: undefined behavior for nullish range options is legit

---

test/index.js
test/iterator-seek-test.js
test/self.js

Closes #269. Tested against `leveldown` (I've got a local branch ready, will push that once this is merged).

Import seek tests from leveldown

---

README.md
test/iterator-range-test.js

Can be released as semver-patch, if you are OK with the plan outlined in https://github.com/Level/abstract-leveldown/issues/318 (I'll close that one after having opened follow-up issues on relevant repos).

Remove range tests that assumed zero-length strings or Buffers meant "not defined"

---

abstract-leveldown.js
test/batch-test.js
test/chained-batch-test.js
test/self.js

Closes #336.
- `db.batch([], callback)` now calls `callback` asynchronously, bypassing `_batch()`
- I considered doing the same for chained batch, by tracking if the batch has operations, but decided not to, so that implementations can choose to ignore certain operations. For example, `batch.del(0)` might be ignored and `abstract-leveldown` would wrongly think there's a queued operation.
- Added abstract tests for asynchronicity of `db.batch([])` (array-form) and `db.batch()` (chained-form)

Fix and test asynchronicity of empty batch

---

README.md
abstract-leveldown.js
test/clear-range-test.js
test/clear-test.js
test/common.js
test/index.js
test/self.js

Start of #236. For early feedback (see comments in code).

Add clear()

---

README.md
abstract-leveldown.js
package.json
test/common.js
test/index.js
test/manifest-test.js
test/self.js

See Level/community#83.
Related work: https://github.com/Level/levelup/pull/674, https://github.com/Level/level-js/pull/179.

Add manifest

---

test/iterator-range-test.js

To try and break https://github.com/Level/leveldown/pull/689/commits/fb7e970ba3dc68d652b0c4be5a038c71c9ed7c70 of https://github.com/Level/leveldown/pull/689.
Tested locally against `leveldown`, `memdown` and `level-js`.

Add more range tests

---

abstract-leveldown.js

Do not rely on the global.Buffer property implicitly.
In some environments like `electron` this global variable
does not exist at all.

src: Import buffer

---

README.md
test/batch-test.js
test/chained-batch-test.js
test/clear-test.js
test/close-test.js
test/common.js
test/del-test.js
test/get-test.js
test/iterator-range-test.js
test/iterator-test.js
test/manifest-test.js
test/open-test.js
test/put-get-del-test.js
test/put-test.js

As well as skipping 'start' and 'end' tests (for `multileveldown`) (see also https://github.com/Level/community/issues/86).
Doesn't change anything for existing `abstract-leveldown` implementations. Before releasing I do want to test it on:
Working towards https://github.com/Level/community/issues/58.

Support running test suite on a levelup db

---

.airtap.yml
package.json

Updates `Buffer` to the latest version as having multiple versions in
the dep tree causes quite a lot of bundle bloat when run in browsers!

chore: update deps

---

README.md
abstract-iterator.js
test/async-iterator-test.js
test/index.js
test/iterator-test.js
test/self.js

Closes #235. You can now do:
```js
try {
for await (const [key, value] of db.iterator()) {
console.log(key)
}
} catch (err) {
console.error(err)
}
```
Supersedes #338, which was just a proof of concept and we've since dropped support of legacy runtimes (Level/community#98) which now allows us to use async generators across the board.

Support `for await...of db.iterator()`

---

README.md
abstract-leveldown.js
lib/common.js
package.json
test/common.js
test/del-test.js
test/get-many-test.js
test/get-test.js
test/index.js
test/iterator-test.js
test/put-get-del-test.js
test/put-test.js
test/self.js
test/util.js

Tested against `leveldown`, `memdown`, `level-js`, `deferred-leveldown`, `encoding-down`, (indirectly) `levelup`, `subleveldown`.
Ref https://github.com/Level/community/issues/101

Add `db.getMany(keys)`
